{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "fraud-detection-engine.fullname" . }}
  labels:
    {{- include "fraud-detection-engine.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name | quote }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind | quote }}
  target:
    name: {{ include "fraud-detection-engine.secretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.externalSecret.data.dbUser.key | quote }}
        {{- if .Values.externalSecret.data.dbUser.property }}
        property: {{ .Values.externalSecret.data.dbUser.property | quote }}
        {{- end }}
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.data.dbPassword.key | quote }}
        {{- if .Values.externalSecret.data.dbPassword.property }}
        property: {{ .Values.externalSecret.data.dbPassword.property | quote }}
        {{- end }}
    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.externalSecret.data.jwtSecret.key | quote }}
        {{- if .Values.externalSecret.data.jwtSecret.property }}
        property: {{ .Values.externalSecret.data.jwtSecret.property | quote }}
        {{- end }}
    - secretKey: JWT_ISSUER
      remoteRef:
        key: {{ .Values.externalSecret.data.jwtIssuer.key | quote }}
        {{- if .Values.externalSecret.data.jwtIssuer.property }}
        property: {{ .Values.externalSecret.data.jwtIssuer.property | quote }}
        {{- end }}
    - secretKey: JWT_AUDIENCE
      remoteRef:
        key: {{ .Values.externalSecret.data.jwtAudience.key | quote }}
        {{- if .Values.externalSecret.data.jwtAudience.property }}
        property: {{ .Values.externalSecret.data.jwtAudience.property | quote }}
        {{- end }}
{{- end }}
